### ISSUE TITLE
Are there reserved/unused tokens for developers?

### ISSUE THREAD

**Issue by Qubitium** [google/gemma_pytorch#12]
Due to BPE vocabulary unable to dynamically expand after training, for finetuning,  some BPE tokenizer based models such as Qwen reserved 2k extra unused tokens at the end for developers to use as they see fit. 

Does Gemma have a list of internally unused tokens? 

Sometimes model makers resize a vocab to a nice gpu-friendly multiple which creates unused tokens or intentially leave some unused tokens such as Qwen.

**Comment by Qubitium** [comment]
Thank you! Exactly what we are looking for.

**Comment by HrushikeshPawar** [comment]
Are there any pointers or guidelines on how we can make use of these `<unusedXX>` tokens?
How can one make use of them while finetuning?
