### ISSUE TITLE
Inconsistencies in Reported Dimensions and Configuration Files

### ISSUE THREAD

**Issue by fvarno** [google/gemma_pytorch#2]
In Table 1 of [Gemma Technical Report](https://storage.googleapis.com/deepmind-media/gemma/gemma-report.pdf) `Feedforward hidden dims` are listed as 32768 and 49152 for the 2B and 7B models, respectively. However, these figures do not align with the numbers provided in the configuration files for the [for 7B model](https://github.com/google/gemma_pytorch/blob/main/gemma/config.py#L47) and [2B model](https://github.com/google/gemma_pytorch/blob/main/gemma/config.py#L74). This discrepancy leads me to wonder whether I am comparing the incorrect figures, if there is an error in the report, or if the experiments were conducted using different configuration files. Should the numbers in the technical report require revision, it would also be necessary to update the reported total number of parameters accordingly.
![image](https://github.com/google/gemma_pytorch/assets/40249495/ce561fba-7dcb-4c6b-ae2f-0305844f1848)

**Comment by pengchongjin** [comment]
The feed forward hidden dims in the table of this tech report is the sum of hidden dim of gate projection and up projection, which is 2X of `intermediate_size` in the code.

Hope that explains.
