### ISSUE TITLE
[Question] Embeddings normalization by sqrt(hidden_size)

### ISSUE THREAD

**Issue by Andrei-Aksionov** [google/gemma_pytorch#29]
Hello there 👋 

Thanks for the repo.
But I have one question: why do we need to scale up (normalize) token embeddings? 
https://github.com/google/gemma_pytorch/blob/01062c9ef4cf89ac0c985b25a734164ede017d0b/gemma/model.py#L431-L432

Unfortunately, I cannot find an answer anywhere.

**Comment by crolequi** [comment]
https://arxiv.org/pdf/1706.03762.pdf
See 3.4

**Comment by Andrei-Aksionov** [comment]
Thanks @crolequi for the response.
In the paper it just stated that they multiplied weights, but didn't explain why exactly.
<img width="725" alt="Screenshot 2024-03-05 at 12 39 29 PM" src="https://github.com/google/gemma_pytorch/assets/58434077/670fc8d3-4bf4-4d65-99ba-a7db4f3e38b0">

**Comment by suryabhupa** [comment]
that's a great question! it's been asked a few times, and there are some possible explanations (but no clear reason): https://datascience.stackexchange.com/questions/87906/transformer-model-why-are-word-embeddings-scaled-before-adding-positional-encod.

**Comment by Andrei-Aksionov** [comment]
Thanks @suryabhupa for the link. It helped a lot.
