### ISSUE TITLE
is it possible to convert gemma_pytorch to onnx to tflite?

### ISSUE THREAD

**Issue by nyadla-sys** [google/gemma_pytorch#30]
is it possible to convert gemma_pytorch to onnx to tflite?

**Comment by suryabhupa** [comment]
cc @pengchongjin any guidance here?

**Comment by pengchongjin** [comment]
Unfortunately, we haven't convert pytorch checkpoint to onnx or tflite ourselves. 

Maybe you can follow the standard guides `torch.onnx`: https://pytorch.org/docs/stable/onnx.html and `tf-lite` to try the conversion.

**Comment by Gopi-Uppari** [comment]
Hi @nyadla-sys,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by Gopi-Uppari** [comment]
Hi @nyadla-sys,

Closing this issue due to lack of recent activity,  Please feel free reopen if this is still a valid request. 

Thank you!
