### ISSUE TITLE
Inconsistency between PyTorch and JAX implementation

### ISSUE THREAD

**Issue by aboros98** [google/gemma_pytorch#33]
Hello! 

In the PyTorch implementation, in the MLP, exact GeLU is used as a gating function.

![image](https://github.com/google/gemma_pytorch/assets/78988918/84e902b1-8de1-4030-af73-f191598aa875)

![image](https://github.com/google/gemma_pytorch/assets/78988918/463c0ed1-5c41-473c-92a8-282ecbce753b)

In the JAX version, the approximate gelu is used.

![image](https://github.com/google/gemma_pytorch/assets/78988918/ccb2f80f-f340-4fbd-90a6-c636330c8103)
![image](https://github.com/google/gemma_pytorch/assets/78988918/d8e99898-acd3-47fb-83e8-b134715fc98a)

Could you please clarify which version is the correct one?

**Comment by pengchongjin** [comment]
I see this PR is fixing it, will help land it soon.
https://github.com/google/gemma_pytorch/pull/37

**Comment by pengchongjin** [comment]
PR is checked in. Closing this.
