### ISSUE TITLE
A web runtime supported version of gemma is really needed and high value

### ISSUE THREAD

**Issue by Zwe1** [google/gemma_pytorch#4]
It's really a wild potential to use gemma in web runtime, so please provide a web runtime version (wasm or typescript version will be better) for the users!
Thanks a lot and look forward to it!!!!

**Comment by gustheman** [comment]
you can run Gemma models with MediaPipe in the web: https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference

**Comment by Gopi-Uppari** [comment]
Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by Gopi-Uppari** [comment]
Closing this issue due to lack of recent activity,  Please reopen if this is still a valid request. 

Thank you!
