### ISSUE TITLE
Is max_position_embeddings=8096 neccessary in 2b model?

### ISSUE THREAD

**Issue by agiwave** [google/gemma_pytorch#41]
I just try to do some small changes on model '2b'
1, Limit max_position_embeddings from 8096 to 256. :)
2, Trim kv-cache in GemmaAttention to max_position_embeddings(256).
3, Unlimit the output length of model.generate
The generate work is still working fine and can generate about 400 tokens for question "The life meaning is".

Is that means?
1, The too old kv-caches is not neccessary and the model can store and compress long-context info into 256 kv-cache(18-layers)?
2, Could have a try on training model this way(only max 256 kv-cache)?
3, If above is true, Does this means that we can decrease the training and generating complexity tremendously from O(L*L*D) to O(256*L*D) = O(L*D)?

**Comment by agiwave** [comment]
Maybe we can extend Gemma context-length to unlimited size(depend on the compress-rate) in this way(with limited kv-cache length - 256 or little more?) in linear complexity.

**Comment by pengchongjin** [comment]
> 2, Trim kv-cache in GemmaAttention to max_position_embeddings(256).
Do you mean using a slide window of size 256 as you generate the output tokens?

I think this is an interesting observation. I believe there are some related work in the literature which tries to use sliding window to extrapolate the context. It sounds like you are doing similar things.

**Comment by agiwave** [comment]
Yeah.  I try to limit max_position_embeddings to 256 and generate beyond 400 tokens answer. It looks work well. I wish the model can compress the context info far beyond 256 token first. So, I tried it. But, unfortunately. I told the model my name first, and followed by 300 tokens about another infos. At last , I try to ask Gemma " Do you know what's my name". Gemma haven't give me my right name. So gemma has no sliding windows memory. This test only work in 256 tokens（Attention scope）. Emm, a little bit lose here :).

**Comment by agiwave** [comment]
I want doing some LLM work, But for resource limitation, I can't. So, just waiting your great works on it:) Maybe someday, your Gemma can have memories, that will be a very very great progress.  I guess these kind of model architecture is coming soon. And the model can learn message without tremendous learning and long-length-context at all, maybe just one time learning. Keep going:)

**Comment by Gopi-Uppari** [comment]
Hi @agiwave,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by Gopi-Uppari** [comment]
Hi @agiwave,

Closing this issue due to lack of recent activity,  Please feel free reopen if this is still a valid request. 

Thank you!
