### ISSUE TITLE
--quant always returns True

### ISSUE THREAD

**Issue by nakkapeddi** [google/gemma_pytorch#5]
Regardless of what value is passed in, the --quant argument will always return True. Python will cast the string to always true, even if you have set it to false:

```
$ docker run -t --rm     --gpus all     -v ${CKPT_PATH}:/tmp/ckpt     ${DOCKER_URI}     python scripts/run.py     --device=cuda     --ckpt=/tmp/ckpt  --quant="false" --variant="${VARIANT}"  --prompt="${PROMPT}"                                                                                                                  
True

>>> bool("foo")
True
>>> bool("false")
True
>>> bool("0")
True

```
Solution is to have a portable strtobool utility, and I suggest having a contract of something like "0", "1", "true", "false". Bash is stringly typed and Python is duck typed, so it leads to this kind of issues.

**Comment by pengchongjin** [comment]
Hmm, can you try `--quant=false` without the double quotes? I think the double quota might be problematic.

**Comment by pengchongjin** [comment]
Looks like simply setting `--quant=false` didn't work.

**Comment by SedrickWang** [comment]
`"--quant=$false"` works.

**Comment by SedrickWang** [comment]
Replace 'parser.add_argument("--quant", type=bool, default=False)' with 'parser.add_argument("--quant", action='store_true')'. If you include `--quant` on the command line, `args.quant` will be set to `True`. If you do not include `--quant`, then `args.quant` will be set to `False`. 
Here is an example for using quantified gemma model: 
```bash
python scripts/run.py --device=cuda --ckpt=/tmp/ckpt --variant="2b" --quant --prompt="Hi, gemma."
```

**Comment by michaelmoynihan** [comment]
Thanks for the fix, Pengchong! Looks like this can be closed.
