### ISSUE TITLE
Error when run docker/Dockerfile

### ISSUE THREAD

**Issue by Cguanqin** [google/gemma_pytorch#53]
ERROR: failed to solve: process "/bin/sh -c pip install -e ." did not complete successfully: exit code: 1

**Comment by pengchongjin** [comment]
@Cguanqin, could you please provide more information for this error?

 - the model variant
 - hardware platform
 - command you used

Thanks

**Comment by Gopi-Uppari** [comment]
Hi @Cguanqin,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.
