### ISSUE TITLE
Gemma finetuning formatting 

### ISSUE THREAD

**Issue by mostafamdy** [google/gemma_pytorch#60]
Hi,
I'm a bit confused. Should I use Gemma formatting tags during fine-tuning https://ai.google.dev/gemma/docs/formatting , or should I use this template: 'Instruction:\n{instruction}\n\nResponse:\n{response}' I found this template in many notebooks

**Comment by Gopi-Uppari** [comment]
Hi @mostafamdy,

If you're working in an environment that supports or requires the Gemma format, it's best to follow the official documentation. The 'Instruction-Response' template, on the other hand, is commonly used for fine-tuning instruction-following models. You can also compare the outputs from both approaches and choose the one that produces the desired results.

Thank you.

**Comment by Gopi-Uppari** [comment]
Hi @mostafamdy,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by Gopi-Uppari** [comment]
Closing this issue as stale. Feel free to re-open if the issue still persists. 

Thank you!
