### ISSUE TITLE
How to solve the 'RESOURCE_EXHAUSTED' error when loading 'gemma2_instruct_2b_en' (the script is from kaggle and runs on colab with TPU)?

### ISSUE THREAD

**Issue by nicewang** [google/gemma_pytorch#72]
How to solve the 'RESOURCE_EXHAUSTED' error when loading 'gemma2_instruct_2b_en' (the script is from kaggle and runs on colab with TPU)? Errors shown following:
![Image](https://github.com/user-attachments/assets/8f27ae20-675f-4fa5-bb05-605d1c73ab7c)

The environment is the colab opened from kaggle notebook, and with TPU v2-8 accelerator, and:
RAM：6.02 GB/334.56 GB
Disk：22.13 GB/225.33 GB

Had changed the XLA_PYTHON_CLIENT_MEM_FRACTION from 0.1 to 1.00, but seems useless:
![Image](https://github.com/user-attachments/assets/e13255b5-4da1-4f65-b2a4-ec4660767016)

**Comment by Gopi-Uppari** [comment]
Hi 

I encountered the same issue when running on Google Colab with the runtime set to **TPU v2-8**, but it worked fine on Kaggle with the **TPU VM v3-8** runtime. Could you please refer to this [Gist file](https://colab.research.google.com/gist/Gopi-Uppari/947c709a0cbf13ef64ada7714e5185c1/github_issue_72.ipynb) 

@pengchongjin Could you please take a look at the issue.

Thank you.

**Comment by nicewang** [comment]
Thx @Gopi-Uppari ,

I had followed your shared colab file, and finally succeeded both on Kaggle with **TPU VM v3-8** and colab with **TPU v2-8**.

Further, I am just curious about whether there is any dependencies conflicts issues? since I just changed my dependencies installation from:
![Image](https://github.com/user-attachments/assets/aa1b26b7-d25c-4092-acc1-f45f8e79242e)
to:
![Image](https://github.com/user-attachments/assets/a353650e-8a11-455e-ab34-3ef4d71d86d0)

**Comment by Gopi-Uppari** [comment]
Hi @nicewang,

I'm glad it worked for you, that could possibly be the reason for the dependency conflicts.

Thank you.

**Comment by Gopi-Uppari** [comment]
Closing this issue as stale. Feel free to re-open if the issue still persists. 

Thank you!
